ktor:
  application:
    modules:
     # - org.example.ktor.ApplicationKt.module_Routing
      - org.example.ktor.ApplicationKt.module_Serialization
  deployment:
    port: 7788
    host: "127.0.0.1"

