ktor:
  application:
    modules:
      - org.example.ktor.ApplicationKt.module_Serialization
  deployment:
    port: 7788
    host: "127.0.0.1"
    ### https://api.ktor.io/ktor-server/ktor-server-netty/io.ktor.server.netty/-netty-application-engine/-configuration/index.html?_cl=MTsxOzE7UXdnblZJc0QxRXFIQkhWZEZPdGNnaGdqa2dwMGhiWnBjOWJFTTNIZmNzR015cHl6TERTTnVqeGR2ME1uVzl4czs=
    ## options common for all engines
    # connectionGroupSize: 2
    # workerGroupSize: 5
    # callGroupSize: 10
    # shutdownGracePeriod: 2000
    # shutdownTimeout: 3000
    ## Netty-specific options
    # maxInitialLineLength: 2048
    # maxHeaderSize: 1024
    # maxChunkSize: 42

# time sec * 1000
storage:
  dbName: "sqlite"
  dbcp:
    maxPoolSize: "10"
    maxLifetime: "1800000" # 30 MIN
    connectionTimeout: "30000" # 30 SEC
    validationTimeout: "5000" # 5 SEC
    idleTimeout: "600000" # 10 MIN
    initializationFailTimeout: "1"
    isAutoCommit: "false"
    keepaliveTime: "120000" # 2 MIN
  database:
    h2:
      driverClassName: "org.h2.Driver"
      jdbcURL: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
      user: "root"
      password: ""
    sqlite:
      driverClassName: "org.sqlite.JDBC"
      jdbcURL: "jdbc:sqlite:/Users/unchil/AndroidStudioProjects/full-stack-task-manager/full-stack-task-manager.sqlite"
